-- KaziLink production database starting point.
-- Run this in a Supabase SQL editor after creating the project.
-- The current Python demo uses SQLite; this schema is the migration target.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  phone text not null,
  role text not null check (role in ('customer','worker','admin')),
  location text,
  created_at timestamptz default now()
);

create table if not exists worker_profiles (
  user_id uuid primary key references profiles(id) on delete cascade,
  trade text not null,
  skills text default '',
  experience integer default 0,
  description text default '',
  photo_url text default '',
  verified boolean default false,
  featured boolean default false,
  rating numeric(3,2) default 0,
  review_count integer default 0
);

create table if not exists jobs (
  id bigint generated by default as identity primary key,
  customer_id uuid references profiles(id) on delete cascade,
  category text not null,
  title text not null,
  description text not null,
  location text not null,
  budget text default '',
  job_date date,
  status text default 'open',
  created_at timestamptz default now()
);

create table if not exists applications (
  id bigint generated by default as identity primary key,
  job_id bigint references jobs(id) on delete cascade,
  worker_id uuid references profiles(id) on delete cascade,
  message text not null,
  status text default 'pending',
  created_at timestamptz default now(),
  unique(job_id, worker_id)
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  customer_id uuid references profiles(id) on delete cascade,
  worker_id uuid references profiles(id) on delete cascade,
  job_id bigint references jobs(id) on delete set null,
  rating integer check(rating between 1 and 5),
  comment text default '',
  created_at timestamptz default now()
);

create table if not exists plans (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  price_ugx integer not null,
  duration_days integer not null,
  active boolean default true
);

insert into plans(code,name,price_ugx,duration_days)
values
('featured','Featured Worker',5000,30),
('premium','Premium Profile',15000,30),
('business','Business Account',30000,30)
on conflict (code) do nothing;
